# Generated by Django 4.1.5 on 2023-01-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
